---
title: "Minhas ações"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyquant)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)


prices <- read.csv("C:/Users/caoli/OneDrive/Documentos/ProjectR/prices.csv") %>%
  mutate(date = as.Date(date))

tabela_periodo <- data.frame(
  periodo = c("1M", "6M", "1A", "10A"),
  dias = c(30, 180, 365, 3650)
)
colours = c(
  "AERI3" = "yellow", "KRSA3" = "green", "CLSC4" = "blue", 
  "FESA4" = "grey", "RIGG34" = "pink", "IGTI3" = "purple", 
  "SLCE3" = "orange", "EZTC3" = "cyan", "ENEV3" = "red", 
  "STBP3" = "black"
)

```

Column {.sidebar}
------------------------------------------------------------------------

```{r}
selectInput(
  "acao", label = "Escolha sua ação",
  choices = c(
  "AERI3","KRSA3","CLSC4","FESA4","RIGG34",
  "IGTI3","SLCE3","EZTC3","ENEV3","STBP3"
  ))
selectInput(
  "periodo", label = "Escolha seu período",
  choices = c("1M", "6M", "1A", "10A")
)
```


Row {data-width=500}
-----------------------------------------------------------------------

### Tendência

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo 
  == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo, symbol == input$acao) %>% 
    ggplot() +
    aes(x= date, y = adjusted, color = symbol) +
    geom_line() +
    scale_color_manual(values = colours) +
    labs(x = "", y = "Cotação") +
    ggtitle(label = input$acao) +
    theme(
      panel.background = element_blank(),
      plot.title = element_text(size=22),
      legend.position = "none"
    )
})
```

### Todas as tendência

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo 
  == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo) %>% 
    ggplot() +
    aes(x= date, y = adjusted, color = symbol) +
    geom_line(size = 1.1) +
    scale_color_manual(values = colours) +
    labs(x = "", y = "Cotação", color = "Ação") +
    theme(panel.background = element_blank())
})

```

Row {data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo 
  == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo, symbol == input$acao) %>% 
    mutate(across(where(is.double), round, digits = 2)) %>% 
    arrange(desc(date)) %>% 
     rename(
      Ação = symbol,
      Data = date,
      Abertura = open,
      Máximo = high,
      Mínimo = low,
      Fechamento = close,
      Volume = volume,
      Ajustado = adjusted) %>% 
    datatable(rownames = FALSE)
})
```